version: "3.8"

services:
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - /mnt/efs/db:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  apachephp:
    image: victorburlina016/aula:latest
    environment:
      WEB_DOCUMENT_ROOT: /app
    volumes:
      - /mnt/efs/app:/app
    networks:
      - app-network
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    deploy:
      replicas: 2
      # phpmyadmin n√£o precisa obrigatoriamente ser restrito a manager
    ports:
      - "8081:80"

volumes:
  app_data:
    driver_opts:
      type: "nfs"
      o: "addr=fs-00b34e17b74bde2ce.efs.us-east-1,rw"
      device: ":/app"

  db_data:
    driver_opts:
      type: "nfs"
      o: "addr=fs-00b34e17b74bde2ce.efs.us-east-1,rw"
      device: ":/db"

networks:
  app-network:
    driver: overlay

