version: "3.8"

services:

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager   # Banco só roda no manager

  apachephp:
    image: victorburlina016/aula:2.0
    environment:
      WEB_DOCUMENT_ROOT: /app
    volumes:
      - app_data:/app   # EFS compartilhado
    networks:
      - app-network
    deploy:
      replicas: 5
      placement:
        constraints:
          - node.role == manager   # Somente managers rodam o apache se quiser garantir acesso ao EFS
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    deploy:
      replicas: 2
      # phpmyadmin não precisa obrigatoriamente ser restrito a manager
    ports:
      - "8081:80"

volumes:
  app_data:
    driver_opts:
      type: "nfs"
      o: "addr=fs-00b34e17b74bde2ce.efs.us-east-1,rw"
      device: ":/app"

  db_data:
    driver_opts:
      type: "nfs"
      o: "addr=fs-00b34e17b74bde2ce.efs.us-east-1,rw"
      device: ":/db"

networks:
  app-network:
    driver: overlay
